service: serverless-api-demo
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:440614633701:table/ItemTable

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createItem:
    handler: api/create.handler
    events:
      - httpApi:
          path: /items
          method: post
  updateItem:
    handler: api/update.handler
    events:
      - httpApi:
          path: /items/{id}
          method: put
  findById:
    handler: api/findById.handler
    events:
      - httpApi:
          path: /items/{id}
          method: get
  findAll:
    handler: api/list.handler
    events:
      - httpApi:
          path: /items
          method: get
  delete:
    handler: api/delete.handler
    events:
      - httpApi:
          path: /items/{id}
          method: delete

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ItemTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH